### ISSUE TITLE
!list fern ungenau

### ISSUE THREAD

**Issue by Kobert-P** [TrueDoctor/DiscoBot#10]
!list fern (bzw jetzt !held fern) Gibt eine Liste aller Talente, nicht nur der Fernkampfwaffen.

**Comment by TrueDoctor** [comment]
Die Fernkampfwaffen sind auch keine gesonderten Talente, der command ist funktionell equivalent zu  !list talents

**Comment by Kobert-P** [comment]
Ok, also müsste man die Fernkampftalent namentlich festlegen um es richtig zu machen...
