### ISSUE TITLE
!LE/!AE als Charakter Funktion

### ISSUE THREAD

**Issue by Kobert-P** [TrueDoctor/DiscoBot#3]
Evtl sollte die Logik von !LE und !AE in der Charakter Klasse enthalten sein?

**Comment by TrueDoctor** [comment]
meinst du mit logik sowas wie, nicht weniger als 0, nicht mehr als x?

**Comment by TrueDoctor** [comment]
Wir könnten das auch zu einer generischen Erweiterungsmethode umbauen
