### ISSUE TITLE
Logo flashes on the screen when logging in

### ISSUE THREAD

**Issue by TrueDoctor** [TrueDoctor/DiscoBot#35]

**Comment by TrueKuehli** [comment]
Can you provide more detail, as to what exactly is happening?

**Comment by TrueDoctor** [comment]
sent u a vid

**Comment by TrueDoctor** [comment]
a stretched image of the websites logo appears for some frames on the lower half of the screen. The Website and copyright notice get pushed upwards

**Comment by TrueKuehli** [comment]
Will have to look furter into that, wasn't happening for me yesterday, but might need to debug that, once the server is running again.

**Comment by TrueKuehli** [comment]
Doesn't seem to be happening to me. Made some changes to the way it redirects the page though in Commit https://github.com/TrueDoctor/DiscoBot/commit/852474350bdd708344857488543fc8b912977a89 which MIGHT change that behavior.
