### ISSUE TITLE
Issue with !gm

### ISSUE THREAD

**Issue by Kobert-P** [TrueDoctor/DiscoBot#4]
Folgendes Verhalten muss überprüft werden:

!gm Morla f wurf

TardisBOT - Today at 10:12 AM
Wurfbeile taw:7  
W20: 4 tap: 7

!gm Morla f Bogen

TardisBOT - Today at 10:13 AM
Bot befindet sich nicht in einem Sprachchannel

**Comment by TrueDoctor** [comment]
Stört die "Bot befindet sich..." Fehlermeldung?
