### ISSUE TITLE
Save LE/AE

### ISSUE THREAD

**Issue by Kobert-P** [TrueDoctor/DiscoBot#5]
LE und AE sollten zwischen den Sessions gespeichert werden.

**Comment by TrueDoctor** [comment]
Das könnte rtwas tricky werden, evtl. kann man die Session als Datei abspeichern...

**Comment by TrueDoctor** [comment]
Vielleicht sollten wir auch Charaktere erst wärend des spielens geladen werden, damit alles übersichtlich bleibt und die beim nächsten mal automatisch wieder geladen werden.

**Comment by TrueDoctor** [comment]
We just need the command infrastructure to utillize the session saves and loads

**Comment by TrueDoctor** [comment]
command infrastructure finished
