### ISSUE TITLE
.png is not displayed correctly in animation

### ISSUE THREAD

**Issue by EliasSchaut** [TrueDoctor/DiscoBot#68]
The most .png are not displayed correctly at the following link: https://github.com/TrueDoctor/DiscoBot/tree/animation/webhogg/animation/Designs/Character

**Comment by TrueDoctor** [comment]
Pictures can not be opened when the repo is cloned locally either.
Leading me to suspect, that they are somehow corrupted

**Comment by Ma27** [comment]
https://github.com/TrueDoctor/DiscoBot/commit/f8700b08a0f8744198e8dd60ed562160d0f2dc0a appears to fix the issue.

Feel free to delete the branch after applying this to the other branches :)

**Comment by EliasSchaut** [comment]
fixed .png issue
